services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: kh-pos-db-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kh_pos_lite
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: pos_user
      MYSQL_PASSWORD: pos_password
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - pos-network

  # Laravel API (Development mode)
  api:
    image: php:8.2-fpm
    container_name: kh-pos-api-dev
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: kh_pos_lite
      DB_USERNAME: pos_user
      DB_PASSWORD: pos_password
      APP_ENV: local
      APP_DEBUG: true
    volumes:
      - ./services/api:/var/www/html
      - ./docker/php-dev.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    command: >
      bash -c "
      apt-get update && apt-get install -y git curl libpng-dev libonig-dev libxml2-dev zip unzip nodejs npm &&
      docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd &&
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      composer install &&
      npm install &&
      php artisan key:generate &&
      php artisan migrate &&
      php-fpm
      "
    depends_on:
      - db
    networks:
      - pos-network

  # Nginx for API
  api-nginx:
    image: nginx:alpine
    container_name: kh-pos-api-nginx-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./services/api:/var/www/html
      - ./docker/api-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - pos-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: kh-pos-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - pos-network

volumes:
  mysql_data_dev:
  redis_data_dev:

networks:
  pos-network:
    driver: bridge